name = "businesscard"
main = "worker.js"
compatibility_date = "2025-09-01"
workers_dev = true
[observability.logs]
enabled = true
[vars]
CONTRACT = "0x8B9dBfe78eEa4b15F0F2b0600CD69FcF6F389668"
RPC_URL = "https://sepolia.era.zksync.dev"
